user:
    resource: 'AppBundle\Controller\UserController'
    type: rest

item:
    resource: 'AppBundle\Controller\ItemController'
    type: rest

order:
    resource: 'AppBundle\Controller\OrderController'
    type: rest