api_v1_get_charger_all:
  path: /all
  controller: AppBundle:Catalog/Charger:getAll
  methods: [GET]

api_v1_add_charger:
  path: /add
  controller: AppBundle:Catalog/Charger:add
  methods: [POST]

api_v1_edit_charger:
  path: /{id}/edit
  controller: AppBundle:Catalog/Charger:edit
  methods: [PUT]
  requirements:
    id: \d+

api_v1_delete_charger:
  path: /{id}/delete
  controller: AppBundle:Catalog/Charger:delete
  methods: [DELETE]
  requirements:
    id: \d+