AppBundle\Entity\Catalog\Watch:
  type: entity
  fields:
    gender:
      type: string
      length: 255
    color:
      type: string
      length: 255
    feature:
      type: string
      length: 255