AppBundle\Entity\User\User:
    type: entity
    table: users
    repositoryClass: AppBundle\Repository\User\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
