<?php

namespace AppBundle\Repository\Catalog;

/**
 * WatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WatchRepository extends \Doctrine\ORM\EntityRepository
{
}
