AppBundle\Entity\Catalog\Phone:
  properties:
    model:
    - Type:
        type: string
        groups: [create, update]
    - NotBlank:
        groups: [create, update]
    os:
    - Type:
        type: string
        groups: [create, update]
    - NotBlank:
        groups: [create, update]
    diagonal:
    - Type:
        type: float
        groups: [create, update]
    - NotBlank:
        groups: [create, update]
    weight:
    - Type:
        type: float
        groups: [create, update]
    - NotBlank:
        groups: [create, update]