AppBundle\Entity\Catalog\Phone:
  properties:
    gender:
    - Type:
        type: string
        groups: [create, update]
    - NotBlank:
        groups: [create, update]
    color:
    - Type:
        type: string
        groups: [create, update]
    - NotBlank:
        groups: [create, update]
    feature:
    - Type:
        type: string
        groups: [create, update]
    - NotBlank:
        groups: [create, update]